'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {autoConnect} from '@unicitylabs/sphere-sdk/connect/browser';
import {SPHERE_NETWORKS} from '@unicitylabs/sphere-sdk/connect';

const SPHERE_URL='https://sphere.unicity.network';
const UCT_COIN_ID='f581d30f593e4b369d684a4563b5246f07b1d265f7178a2c0a82b81f39c24dc0';
const DEPOSIT_UCT=5;
const ATTEMPTS_PER_DEPOSIT=20;
const POOL_SHARE=0.5;
const LS='uct-dash-simple-v1';

type Client=Awaited<ReturnType<typeof autoConnect>>['client'];
type Score={address:string;distance:number;time:number};
type Store={wallets:Record<string,{attempts:number;deposited:number}>;scores:Score[];pool:number};
const empty:Store={wallets:{},scores:[],pool:0};
function short(s:string){return s.length>18?`${s.slice(0,9)}…${s.slice(-7)}`:s}
function load():Store{try{return JSON.parse(localStorage.getItem(LS)||'null')||empty}catch{return empty}}
function save(s:Store){localStorage.setItem(LS,JSON.stringify(s))}
function baseUnits(n:number){return BigInt(n)*10n**18n}
function week(){const d=new Date();const day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day);return d.toISOString().slice(0,10)}

export default function Home(){
 const canvasRef=useRef<HTMLCanvasElement|null>(null);const clientRef=useRef<Client|null>(null);const disconnectRef=useRef<(()=>Promise<void>)|null>(null);
 const [address,setAddress]=useState('');const [connecting,setConnecting]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [attempts,setAttempts]=useState(0);const [distance,setDistance]=useState(0);const [playing,setPlaying]=useState(false);const [gameOver,setGameOver]=useState(false);const [leader,setLeader]=useState<Score[]>([]);const [pool,setPool]=useState(0);
 const gameRef=useRef({running:false,dead:false,start:0,distance:0,vy:0,y:0,last:0});
 const refresh=useCallback((a=address)=>{const s=load();setAttempts(a?s.wallets[a]?.attempts||0:0);setPool(s.pool);setLeader([...s.scores].sort((x,y)=>y.distance-x.distance).slice(0,50))},[address]);
 useEffect(()=>{refresh()},[refresh]);
 const connect=useCallback(async()=>{setError('');setConnecting(true);try{const r=await autoConnect({dapp:{name:'UCT Dash',url:location.origin},network:SPHERE_NETWORKS.testnet2,walletUrl:SPHERE_URL,permissions:['identity:read','transfer:request'],silent:false});clientRef.current=r.client;disconnectRef.current=r.disconnect;const a=r.connection.identity.chainPubkey;setAddress(a);const s=load();if(!s.wallets[a]){s.wallets[a]={attempts:0,deposited:0};save(s)}setAttempts(s.wallets[a].attempts);refresh(a)}catch(e){setError(e instanceof Error?e.message:'Wallet connection failed')}finally{setConnecting(false)}},[refresh]);
 const disconnect=useCallback(async()=>{try{await disconnectRef.current?.()}catch{}clientRef.current=null;disconnectRef.current=null;setAddress('');setAttempts(0);setPlaying(false)},[]);
 const deposit=useCallback(async()=>{setError('');if(!clientRef.current||!address)return setError('Connect Sphere first.');const treasury=process.env.NEXT_PUBLIC_SPHERE_TREASURY_ADDRESS;if(!treasury)return setError('Treasury belum diisi di Vercel.');setBusy(true);try{await clientRef.current.intent('send',{to:treasury,amount:baseUnits(DEPOSIT_UCT).toString(),coinId:UCT_COIN_ID});const s=load();const w=s.wallets[address]||{attempts:0,deposited:0};w.attempts+=ATTEMPTS_PER_DEPOSIT;w.deposited+=DEPOSIT_UCT;s.wallets[address]=w;s.pool+=DEPOSIT_UCT*POOL_SHARE;save(s);setAttempts(w.attempts);setPool(s.pool);setError('');}catch(e){setError(e instanceof Error?e.message:'Deposit gagal')}finally{setBusy(false)}},[address]);
 const finish=useCallback((d:number)=>{if(!address)return;const s=load();const w=s.wallets[address]||{attempts:0,deposited:0};w.attempts=Math.max(0,w.attempts-1);s.wallets[address]=w;s.scores.push({address,distance:Math.floor(d),time:Date.now()});save(s);setAttempts(w.attempts);setLeader([...s.scores].sort((a,b)=>b.distance-a.distance).slice(0,50));setPlaying(false);setGameOver(true)},[address]);
 const start=()=>{if(!address)return setError('Connect Sphere dulu.');if(attempts<=0)return setError('Percobaan habis. Deposit 5 UCT untuk 20 percobaan.');const g=gameRef.current;g.running=true;g.dead=false;g.start=performance.now();g.distance=0;g.vy=0;g.y=372;g.last=performance.now();setDistance(0);setGameOver(false);setPlaying(true)};
 const jump=useCallback(()=>{if(gameRef.current.running&&!gameRef.current.dead)gameRef.current.vy=-760},[]);
 useEffect(()=>{const c=canvasRef.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;const img=new Image();img.src='/player.jpeg';let raf=0;const W=960,H=540,ground=430;const obs:Array<{x:number,w:number,h:number}>=[];let spawn=500;function loop(){const now=performance.now();const g=gameRef.current;const dt=Math.min(.032,(now-g.last)/1000||.016);g.last=now;ctx.clearRect(0,0,W,H);const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#ff8a2b');grad.addColorStop(.72,'#df5d16');grad.addColorStop(1,'#a83f13');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.12)';for(let i=0;i<24;i++){const x=((i*137-g.distance*.22)%W+W)%W;ctx.fillRect(x,0,2,H*.6)}ctx.fillStyle='#171920';ctx.fillRect(0,ground,W,H-ground);ctx.fillStyle='#272a33';ctx.fillRect(0,ground-7,W,7);if(g.running){const speed=300+Math.min(180,g.distance/10);g.distance+=speed*dt;setDistance(Math.floor(g.distance));g.vy+=1850*dt;g.y+=g.vy*dt;if(g.y>ground-58){g.y=ground-58;g.vy=0}spawn-=speed*dt;if(spawn<=0){const h=34+Math.random()*58;obs.push({x:W+20,w:28+Math.random()*30,h});spawn=260+Math.random()*220}for(const o of obs)o.x-=speed*dt;while(obs[0]?.x<-80)obs.shift();for(const o of obs){if(110+58-8>o.x&&110+8<o.x+o.w&&g.y+58-8>ground-o.h){g.running=false;g.dead=true;finish(g.distance);break}}}for(const o of obs){ctx.fillStyle='#15171d';ctx.beginPath();ctx.moveTo(o.x,ground);ctx.lineTo(o.x+o.w/2,ground-o.h);ctx.lineTo(o.x+o.w,ground);ctx.closePath();ctx.fill()}if(img.complete)ctx.drawImage(img,110,g.y,58,58);ctx.fillStyle='rgba(0,0,0,.3)';ctx.fillRect(20,18,210,48);ctx.fillStyle='#fff';ctx.font='900 22px system-ui';ctx.fillText(`${Math.floor(g.distance)} m`,34,50);raf=requestAnimationFrame(loop)}
 const h=(e:KeyboardEvent)=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();jump()}};window.addEventListener('keydown',h);c.addEventListener('pointerdown',jump);raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);window.removeEventListener('keydown',h);c.removeEventListener('pointerdown',jump)}},[finish,jump]);
 return <main className="shell"><div className="topbar"><div className="brand"><span className="dot"/>UCT DASH</div><div className="wallet">{address?<><span className="small">{short(address)}</span><button className="btn" onClick={disconnect}>Disconnect</button></>:<button className="btn primary" onClick={connect} disabled={connecting}>{connecting?'Connecting…':'Connect Sphere'}</button>}</div></div><div className="stats"><div className="card"><div className="label">ATTEMPTS</div><div className="value">{attempts}</div></div><div className="card"><div className="label">DISTANCE</div><div className="value">{distance} m</div></div><div className="card"><div className="label">WEEKLY POOL</div><div className="value">{pool.toFixed(2)} UCT</div></div><div className="card"><div className="label">WEEK</div><div className="value">{week()}</div></div></div>{error&&<div className="notice error">{error}</div>}<div className="gameWrap"><canvas ref={canvasRef} width={960} height={540}/>{(!playing||gameOver)&&<div className="overlay"><div className="modal"><h1>{gameOver?'GAME OVER':'READY?'}</h1><p className="muted">{gameOver?`Jarak ${distance} m. Sisa percobaan: ${attempts}.`:'Tap layar untuk lompat. Satu game over = satu percobaan.'}</p><div className="actions"><button className="btn primary" onClick={start} disabled={!address||attempts<=0}>{attempts>0?'PLAY':'NO ATTEMPTS'}</button><button className="btn" onClick={deposit} disabled={!address||busy}>{busy?'Waiting wallet…':'Deposit 5 UCT → 20 tries'}</button></div></div></div>}</div><section className="leader card"><div className="leaderHead"><div><h2>Leaderboard</h2><div className="small">Jarak tertinggi tersimpan di browser ini</div></div><div className="small">50% deposit → pool</div></div><div className="rows">{leader.length?leader.map((r,i)=><div className="row" key={`${r.address}-${r.time}`}><div className="rank">#{i+1}</div><div className="name">{short(r.address)}</div><div><b>{r.distance}</b> m</div></div>):<div className="notice">Belum ada run.</div>}</div></section><div className="footer">Versi sederhana tanpa database. Data attempts, leaderboard, dan pool disimpan di browser perangkat ini. Testnet only.</div></main>}
